# https://just.systems

# Show available commands
@_default:
    just -u --list

# Dump to Brewfile
@dump:
    /bin/rm -f Brewfile && brew bundle dump
    # Blank line before each section comment for readability
    awk 'NR>1 && /^#/{print ""} 1' Brewfile | sponge Brewfile

# Install from Brewfile, removing unlisted packages
@install:
    brew update && brew upgrade --yes
    brew bundle --jobs $(sysctl -n hw.logicalcpu)
    brew bundle cleanup --force && brew cleanup

# Watch for Brewfile and keep syncing
@watch:
    echo Brewfile | entr -c brew bundle -q
