@_default:
    just -u --list

mount_path := "/Volumes/ADV360"

# Block until the keyboard's USB volume is mounted.
wait-for-mount:
    @if [ ! -d "{{mount_path}}" ]; then \
        echo "Waiting for {{mount_path}}…"; \
        while [ ! -d "{{mount_path}}" ]; do sleep 1; done; \
    fi
    @echo "Found {{mount_path}}"

# Download keyboard files from Kinesis, excluding OS volume metadata.
download: wait-for-mount
    rsync -r \
        --exclude='.fseventsd/' \
        --exclude='System Volume Information/' \
        --exclude='._*' \
        {{mount_path}}/ .

# Remove OS metadata files from the keyboard volume.
clean: wait-for-mount
    find {{mount_path}} -type f -name '._*' -delete
    rm -rf {{mount_path}}/.fseventsd "{{mount_path}}/System Volume Information"

# Upload config files to Kinesis
upload: wait-for-mount
   cp layouts/layout1.txt {{mount_path}}/layouts/layout1.txt
