#!/bin/sh -exu

# The directory holding your source code and stack.yaml file:
SRC_DIR=~/Projects/xmonad-testing

# The name of the executable produced by stack.
EXE_NAME=xmonad-testing

# This script will be given a single argument, the path to the executable it
# should produce.
output_file=$1; shift

cd $SRC_DIR
stack build

unlink $output_file || true
ln `stack path --local-install-root`/bin/$EXE_NAME $output_file
