#!/bin/sh -exu

# This script will be given a single argument, the path to the executable it
# should produce. This is usually `/home/j/.xmonad/xmonad-x86_64-linux`
# output_file=$1; shift

cd ~/Projects/xmonad-testing
echo "Rebuilding xmonad config"
stack build

echo "Relinking $1"

unlink $1 || true
ln `stack path --local-install-root`/bin/xmonad-testing $1
