onboarding = false

[experimental]
kitty_graphics = true

[keys]
goto = "prefix+t"
prefix = "ctrl+g"
split_vertical = ["prefix+|", "prefix+\\"]

# Jump jump
switch_workspace = "ctrl+1..9" # Index jump spaces with `⌃n
focus_agent = "prefix+1..9"    # Index jump agents with `⌃G n`
next_tab = ["alt+right"]       # Next and prev tabs with → ←
previous_tab = ["alt+left"]
next_agent = "alt+down"        # agents: next # Next and prev agents with ↓ ↑
previous_agent = "alt+up"      # agents: previous

[[keys.command]]
command = "$SHELL"
height = "95%"
key = "prefix+v"
type = "popup"
width = "95%"

[[keys.command]]
command = "lazygit"
height = "95%"
key = "prefix+g"
type = "popup"
width = "95%"

[session]
resume_agents_on_restore = false

[theme]
auto_switch = false
name = "gruvbox"

[ui]
agent_panel_sort = "priority"
prompt_new_tab_name = false
sidebar_max_width = 40
sidebar_min_width = 40
window_title = "🐏 {workspace} · {terminal_title}"

[ui.sidebar.agents]
row_gap = 1
rows = [["state_icon", "workspace", "tab"], ["terminal_title_stripped"]]

[ui.sidebar.spaces]
row_gap = 1

[ui.sound]
enabled = false

[ui.toast]
clipboard.enabled = false
delivery = "herdr"
herdr.position = "bottom-left"
