onboarding = false

[keys]
prefix = "ctrl+g"
goto = "prefix+t"
split_vertical = ["prefix+|", "prefix+\\"]

[[keys.command]]
key = "prefix+v"
type = "popup"
command = "$SHELL"
width = "95%"
height = "95%"

[[keys.command]]
key = "prefix+g"
type = "popup"
command = "lazygit"
width = "95%"
height = "95%"

[theme]
auto_switch = false
name = "gruvbox"

[ui.sound]
enabled = false

[ui.toast]
delivery = "herdr"
