route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 15m
  receiver: 'ntfy.sh proxy'
receivers:
  - name: 'ntfy.sh proxy'
    webhook_configs:
      - url: 'http://127.0.0.1:9166'
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
