esphome:
  name: devkit

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:
  password: ""

ota:
  platform: esphome
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none

web_server:
  port: 80
  log: false
  ota: false

# Activates prometheus /metrics endpoint
prometheus:

# Devkit has 21/22 for SDA/SCL even though there is an extra CLK pin.
i2c:
  sda: 21
  scl: 22
  scan: true
  id: bus_a

sensor:
  - platform: scd30
    co2:
      name: "SCD30 CO2"
      accuracy_decimals: 1
    temperature:
      name: "SCD30 Temperature"
      accuracy_decimals: 2
    humidity:
      name: "SCD30 Humidity"
      accuracy_decimals: 1
    address: 0x61
    update_interval: 30s
    temperature_offset: 2

