# https://just.systems
# Dependencies: op (1Password CLI), openssl, uv

set lazy

PASSWORD := `op read "op://Private/Raycast Settings Export/password"`
OUT := "/Users/j/Notes/Styx/Files/Raycast"

# Show available commands
@_default:
    just -u --list

# Decode v1.rayconfig to v1.config.json and v1.keys.txt
@decode_1:
    PASSWORD="{{ PASSWORD }}" ./main.py --from v1 --out {{ OUT }}

# Decode V2.rayconfig to v2.config.json and v2.keys.txt
@decode_2:
    PASSWORD="{{ PASSWORD }}" ./main.py --from v2 --out {{ OUT }}
